version: 2
jobs:
    test:
        docker:
            - image: cimg/php:8.1-browsers
            # - image: cimg/mysql:8.0.20-ram

        steps:
            - run:
                  name: 'Installing extensions'
                  command: pecl install xdebug
            - checkout
            - run:
                  name: 'Create .env'
                  command: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - run:
                  name: 'Install composer dependencies'
                  command: composer install -n --prefer-dist
            - run:
                  name: 'Generate application key'
                  command: php artisan key:generate
            - run:
                  name: 'Unit tests (paratest)'
                  command: php artisan test --parallel --processes=$(nproc) --configuration=phpunit.xml --coverage-xml=/tmp/coverage/coverage-xml --coverage-html=/tmp/coverage --log-junit=/tmp/coverage/junit.xml
            - run:
                  name: 'Static Analysis (PHPStan)'
                  command: vendor/bin/phpstan --memory-limit=2G

workflows:
    version: 2
    workflow:
        jobs:
            - test
