version: 2
jobs:
      unit-tests:
        docker:
            - image: cimg/php:8.1-browsers

        steps:
            - run:
                  name: 'Installing extensions'
                  command: sudo pecl install pcov
            - checkout
            - run:
                  name: 'Create .env'
                  command: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - run:
                  name: 'Install composer dependencies'
                  command: composer install -n --prefer-dist
            - run:
                  name: 'Generate application key'
                  command: php artisan key:generate
            - run:
                  name: 'Unit tests (PHPUnit)'
                  command: php artisan test --parallel --processes=$(nproc) --configuration=phpunit.xml --coverage-xml=/tmp/coverage/coverage-xml --coverage-html=/tmp/coverage --log-junit=/tmp/coverage/junit.xml --stop-on-failure
            - run:
                  name: 'Infection tests (Infection PHP)'
                  command: vendor/bin/infection --only-covered --min-covered-msi=100 -j$(nproc) --ignore-msi-with-no-mutations --test-framework-options="--configuration=phpunit.xml" --coverage=/tmp/coverage --skip-initial-tests --no-progress --git-diff-filter=AM

      static-analysis:
        docker:
            - image: cimg/php:8.1-browsers

        steps:
            - checkout
            - run:
                  name: 'Install composer dependencies'
                  command: composer install -n --prefer-dist
            - run:
                  name: 'Static Analysis (PHPStan)'
                  command: vendor/bin/phpstan --memory-limit=2G

      coding-standards:
        docker:
            - image: cimg/php:8.1-browsers

        steps:
            - checkout
            - run:
                  name: 'Install composer dependencies'
                  command: composer install -n --prefer-dist
            - run:
                  name: 'Coding standard check (PHPCS)'
                  command: vendor/bin/phpcs

workflows:
    version: 2
    workflow:
        jobs:
            - unit-tests
            - static-analysis
            - coding-standards
